# Generated by Django 6.0.2 on 2026-03-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barraca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='cuit',
            new_name='telefono',
        ),
    ]
